apiVersion: v2
name: kube-seal
description: A Helm chart for KubeSeal
type: application
version: 1.0.0

dependencies:
- name: sealed-secrets
  version: 2.17.1
  repository: https://bitnami-labs.github.io/sealed-secrets
