apiVersion: v2
name: argo-events
description: A Helm chart for Argo Events - Event-driven workflow automation for Kubernetes
type: application
version: 1.0.0
appVersion: 2.4.13
dependencies:
  - name: argo-events
    version: 2.4.13
    repository: https://argoproj.github.io/argo-helm
