{{- range $secret := .Values.sealedSecrets }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: "{{ $secret.name }}"
  namespace: {{ $.Release.Namespace }}
  labels:
  {{- range $key, $value := $secret.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}

  annotations:
  {{- if $secret.clusterWide }}
    "sealedsecrets.bitnami.com/cluster-wide": "true"
  {{- end }}
spec:
  encryptedData:
    {{- range $key, $value := $secret.data }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  template:
    metadata:
      name: "{{ $secret.name }}"
      namespace: {{ $.Release.Namespace }}
      annotations:
      {{- range $key, $value := $secret.annotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- /* {{- if $secret.annotations }}
        {{- toYaml $secret.annotations | nindent 8 }}
      {{- end }} */}}
      labels:
      {{- range $key, $value := $secret.labels }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
    type: Opaque
{{- end }}
