apiVersion: v2
name: argo-cd
description: A Helm chart for Argo CD 
type: application
appVersion: 1.0.0
version: 1.0.0
dependencies:
- name: argo-cd
  version: 7.8.8
  repository: https://argoproj.github.io/argo-helm
